create table if not exists public.approvals (
  id          bigint generated by default as identity primary key,
  reference   text not null default '',
  title       text not null,
  action_type text not null check (action_type in ('code-merge','budget','contract','deployment','policy')),
  requester   text not null,
  dept        text not null,
  priority    text not null check (priority in ('high','medium','low')),
  risk        text not null check (risk in ('low','medium','high')),
  reason      text not null,
  owner       text not null,
  state       text not null check (state in ('pending','approved','rejected')) default 'pending',
  feedback    text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.audit_log (
  id          bigint generated by default as identity primary key,
  action      text not null,
  entity_type text not null,
  entity_id   text not null,
  actor       text not null,
  details     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.approvals enable row level security;
alter table public.audit_log enable row level security;

create policy "CEO full access on approvals"
  on public.approvals for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

create policy "CEO full access on audit_log"
  on public.audit_log for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');